language: cpp
sudo: required

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt lzlib        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt --force         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq qt5-default qttools5-dev-tools libqt5xmlpatterns5-dev libqt5sql5-mysql libbz2-dev liblzma-dev ; fi
  - sudo pip install matplotlib

before_script:
  - qmake -v

script:
  - make pull
  - make build_3rdparty build_libs_release build_tools_release build_gui_release -j$(nproc)
  - make test_lib test_tools -k -j$(nproc)
