language: cpp
sudo: required

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      install:
        - apt-get update
        - apt-get -y install python-matplotlib qt5-default libqt5xmlpatterns5-dev libqt5sql5-mysql libbz2-dev liblzma-dev
  include:
    - os: osx
      install:
        - brew update
        - brew install qt lzlib
        - brew link qt --force
        - pip install matplotlib

script:
  - make pull
  - make build_3rdparty build_libs_release build_tools_release build_gui_release
  - make -k test_lib test_tools
