#define HTS_CC "gcc"
#define HTS_CPPFLAGS ""
#define HTS_CFLAGS "-Wall -g -O2 -fvisibility=hidden"
#define HTS_LDFLAGS "-fvisibility=hidden "
#define HTS_LIBS "-lregex -llzma -lbz2 -lws2_32 -lz  -lcurl -lcrypto"
